WeaponEffectsConfig = {
    -- Local canonical 2.31 firearm catalog; inventory records only.
    weapons = {
        {record="Items.Preset_Grad_Buck", label="O'Five", category="Sniper rifle"},
        {record="Items.Preset_Burya_Comrade", label="Comrade's Hammer", category="Revolver"},
        {record="Items.Preset_Chao_Default", label="A-22B Chao", category="Pistol"},
        {record="Items.Preset_Achilles_Collectible", label="Achilles x-MOD2", category="Precision rifle"},
        {record="Items.Preset_Pozhar_AirDrop", label="Alabai", category="Shotgun"},
        {record="Items.Preset_Kenshin_Spy", label="Ambition", category="Pistol"},
        {record="Items.Preset_Overture_Cassidy", label="Amnesty", category="Revolver"},
        {record="Items.Preset_Crusher_Amazon", label="Amstaff", category="Shotgun"},
        {record="Items.Preset_Kenshin_Frank", label="Apparition", category="Pistol"},
        {record="Items.Preset_Lexington_Toygun", label="AR Raygun Supreme 9000", category="Pistol"},
        {record="Items.Preset_Overture_Kerry", label="Archangel", category="Revolver"},
        {record="Items.Preset_Ashura_Default", label="Ashura", category="Sniper rifle"},
        {record="Items.Preset_Zhuo_Eight_Star", label="Ba Xing Chong", category="Shotgun"},
        {record="Items.Preset_Metel_Kurt", label="Bald Eagle", category="Revolver"},
        {record="Items.Preset_Tactician_Dino", label="Bloody Maria", category="Shotgun"},
        {record="Items.Preset_Grad_AirDrop", label="Borzaya", category="Sniper rifle"},
        {record="Items.Preset_Nekomata_Breakthrough", label="Breakthrough", category="Sniper rifle"},
        {record="Items.Preset_Pulsar_Buzzsaw", label="Buzzsaw", category="Submachine gun"},
        {record="Items.Preset_Umbra_Bebe", label="Carmen", category="Assault rifle"},
        {record="Items.Preset_Carnage_Default", label="Carnage", category="Shotgun"},
        {record="Items.Preset_Grit_Amazon", label="Catahoula", category="Pistol"},
        {record="Items.Preset_Kenshin_Royce", label="Chaos", category="Pistol"},
        {record="Items.Preset_Unity_Angelica", label="Cheetah", category="Pistol"},
        {record="Items.Preset_Warden_Amazon", label="Chesapeake", category="Submachine gun"},
        {record="Items.Preset_Kyubi_Amazon", label="Chinook", category="Assault rifle"},
        {record="Items.Preset_Overture_River", label="Crash", category="Revolver"},
        {record="Items.Preset_Crusher_Default", label="Crusher", category="Shotgun"},
        {record="Items.Preset_Copperhead_Default", label="D5 Copperhead", category="Assault rifle"},
        {record="Items.Preset_Sidewinder_Default", label="D5 Sidewinder", category="Assault rifle"},
        {record="Items.Preset_Umbra_Default", label="DA8 Umbra", category="Assault rifle"},
        {record="Items.Preset_Satara_Default", label="DB-2 Satara", category="Double-barrel shotgun"},
        {record="Items.Preset_Testera_Default", label="DB-2 Testera", category="Double-barrel shotgun"},
        {record="Items.Preset_Igla_Default", label="DB-4 Igla", category="Double-barrel shotgun"},
        {record="Items.Preset_Palica_Default", label="DB-4 Palica", category="Double-barrel shotgun"},
        {record="Items.Preset_Nue_Maiko", label="Death and Taxes", category="Pistol"},
        {record="Items.Preset_Testera_Nicolas", label="Dezerter", category="Double-barrel shotgun"},
        {record="Items.Preset_Defender_Kurt", label="Dingo", category="Light machine gun"},
        {record="Items.Preset_Sidewinder_Divided", label="Divided We Stand", category="Assault rifle"},
        {record="Items.Preset_Nova_Doom_Doom", label="Doom Doom", category="Revolver"},
        {record="Items.Preset_Quasar_Default", label="DR-12 Quasar", category="Revolver"},
        {record="Items.Preset_Nova_Default", label="DR5 Nova", category="Revolver"},
        {record="Items.Preset_Pulsar_Default", label="DS1 Pulsar", category="Submachine gun"},
        {record="Items.Preset_Q001_Lexington", label="Dying Night", category="Pistol"},
        {record="Items.Preset_Borg4a_HauntedGun", label="Erebus", category="Submachine gun"},
        {record="Items.Preset_Saratoga_Maelstrom", label="Fenrir", category="Submachine gun"},
        {record="Items.Preset_Nekomata_Amazon", label="Foxhound", category="Sniper rifle"},
        {record="Items.Preset_Dian_Default", label="G-58 Dian", category="Submachine gun"},
        {record="Items.Preset_Yukimura_Kiji", label="Genjiroh", category="Pistol"},
        {record="Items.Preset_Quasar_Baron", label="Gris-Gris", category="Revolver"},
        {record="Items.Preset_Guillotine_Default", label="Guillotine", category="Submachine gun"},
        {record="Items.Preset_Guillotine_Collectible", label="Guillotine x-MOD2", category="Submachine gun"},
        {record="Items.Preset_Carnage_Edgerunners", label="Guts", category="Shotgun"},
        {record="Items.Preset_Grit_Default", label="HA-4 Grit", category="Pistol"},
        {record="Items.Preset_Kyubi_Myers", label="Hawk", category="Assault rifle"},
        {record="Items.Preset_Unity_Agent", label="Her Majesty", category="Pistol"},
        {record="Items.Preset_Hercules_Default", label="Hercules 3AX", category="Assault rifle"},
        {record="Items.Preset_Yukimura_Default", label="HJKE-11 Yukimura", category="Pistol"},
        {record="Items.Preset_Masamune_Default", label="HJSH-18 Masamune", category="Assault rifle"},
        {record="Items.Preset_Kolac_Tiny_Mike", label="Hypercritical", category="Precision rifle"},
        {record="Items.Preset_Kenshin_Default", label="JKE-X2 Kenshin", category="Pistol"},
        {record="Items.Silverhand_Malorian", label="Johnny's Handgun", category="Pistol"},
        {record="Items.Preset_Kappa_Default", label="Kappa", category="Pistol"},
        {record="Items.Preset_Kappa_Legendary", label="Kappa x-MOD2", category="Pistol"},
        {record="Items.Preset_Kolac_Default", label="Kolac", category="Precision rifle"},
        {record="Items.Preset_Liberty_Yorinobu", label="Kongou", category="Pistol"},
        {record="Items.Preset_Kyubi_Default", label="Kyubi", category="Assault rifle"},
        {record="Items.Preset_Kyubi_Legendary", label="Kyubi x-MOD2", category="Assault rifle"},
        {record="Items.Preset_Zhuo_Default", label="L-69 Zhuo", category="Shotgun"},
        {record="Items.Preset_Nue_Jackie", label="La Chingona Dorada", category="Pistol"},
        {record="Items.Preset_Burya_AirDrop", label="Laika", category="Revolver"},
        {record="Items.Preset_Lexington_Shooting_Competition", label="Lexington x-MOD2", category="Pistol"},
        {record="Items.Preset_Liberty_Default", label="Liberty", category="Pistol"},
        {record="Items.Preset_Omaha_Suzie", label="Lizzie", category="Pistol"},
        {record="Items.Preset_Lexington_Default", label="M-10AF Lexington", category="Pistol"},
        {record="Items.Preset_Achilles_Default", label="M-179e Achilles", category="Precision rifle"},
        {record="Items.q115_corpo_rifle", label="M-179 Achilles (modified)", category="Precision rifle"},
        {record="Items.Preset_Omaha_Default", label="M-76e Omaha", category="Pistol"},
        {record="Items.Preset_Tactician_Default", label="M2038 Tactician", category="Shotgun"},
        {record="Items.Preset_Defender_Default", label="M2067 Defender", category="Light machine gun"},
        {record="Items.Preset_Saratoga_Default", label="M221 Saratoga", category="Submachine gun"},
        {record="Items.Preset_Ajax_Default", label="M251s Ajax", category="Assault rifle"},
        {record="Items.Preset_MA70_Default", label="MA70 HB", category="Light machine gun"},
        {record="Items.Preset_MA70_Collectible", label="MA70 HB x-MOD2", category="Light machine gun"},
        {record="Items.Preset_Silverhand_3516", label="Malorian Arms 3516", category="Pistol"},
        {record="Items.Preset_Nova_Hitman", label="Mancinella", category="Revolver"},
        {record="Items.Preset_Metel_Default", label="Metel", category="Revolver"},
        {record="Items.Preset_Ticon_Default", label="Militech Ticon", category="Pistol"},
        {record="Items.Preset_Ajax_Moron", label="Moron Labe", category="Assault rifle"},
        {record="Items.Preset_Carnage_Mox", label="Mox", category="Shotgun"},
        {record="Items.Preset_Osprey_Default", label="NDI Osprey", category="Sniper rifle"},
        {record="Items.Preset_Nekomata_Default", label="Nekomata", category="Sniper rifle"},
        {record="Items.Preset_Masamune_Arasaka_2020", label="Nowaki", category="Assault rifle"},
        {record="Items.Preset_Nue_Default", label="Nue", category="Pistol"},
        {record="Items.Preset_Chao_VooDoo", label="Ogou", category="Pistol"},
        {record="Items.Preset_Overture_Dante", label="Ol' Reliable", category="Revolver"},
        {record="Items.Preset_Satara_Brick", label="Order", category="Double-barrel shotgun"},
        {record="Items.Preset_Overture_Default", label="Overture", category="Revolver"},
        {record="Items.Preset_Grad_Panam", label="Overwatch", category="Sniper rifle"},
        {record="Items.Preset_Ticon_Reed", label="Pariahh", category="Pistol"},
        {record="Items.Preset_Kappa_George", label="Peacekeeper", category="Pistol"},
        {record="Items.Preset_Ajax_Amazon", label="Pit Bull", category="Assault rifle"},
        {record="Items.Preset_Warden_Boris", label="Pizdets", category="Submachine gun"},
        {record="Items.Preset_Liberty_Dex", label="Plan B", category="Pistol"},
        {record="Items.Preset_Pozhar_Legendary", label="Pozhar x-MOD2", category="Shotgun"},
        {record="Items.Preset_Masamune_Rogue", label="Prejudice", category="Assault rifle"},
        {record="Items.Preset_Liberty_Rogue", label="Pride", category="Pistol"},
        {record="Items.Preset_Saratoga_Raffen", label="Problem Solver", category="Submachine gun"},
        {record="Items.Preset_Shingen_Prototype", label="Prototype: Shingen Mark V", category="Submachine gun"},
        {record="Items.Preset_Copperhead_Genesis", label="Psalm 11:6", category="Assault rifle"},
        {record="Items.Preset_Senkoh_Prototype", label="Raiju", category="Submachine gun"},
        {record="Items.Preset_Tech_Sniper_Rifle_Default", label="Rasetsu", category="Sniper rifle"},
        {record="Items.Preset_Nue_Bree", label="Riskit", category="Pistol"},
        {record="Items.Preset_Lexington_Rook", label="Rook", category="Pistol"},
        {record="Items.Preset_Overture_Dodger", label="Rosco", category="Revolver"},
        {record="Items.Preset_Burya_Default", label="RT-46 Burya", category="Revolver"},
        {record="Items.Preset_Ticon_Gwent", label="Scorch", category="Pistol"},
        {record="Items.Preset_Senkoh_Default", label="Senkoh LX", category="Submachine gun"},
        {record="Items.Preset_Liberty_Padre", label="Seraph", category="Pistol"},
        {record="Items.Preset_Saratoga_Arasaka_2020", label="Shigure", category="Submachine gun"},
        {record="Items.Silenced_Lexington", label="Silenced M-10AF Lexington", category="Pistol"},
        {record="Items.Preset_Yukimura_Skippy", label="Skippy", category="Pistol"},
        {record="Items.Preset_Base_Slaughtomatic", label="Slaught-O-Matic", category="Pistol"},
        {record="Items.Preset_Sor22_Default", label="SOR-22", category="Precision rifle"},
        {record="Items.Preset_Igla_Sovereign", label="Sovereign", category="Double-barrel shotgun"},
        {record="Items.Preset_Grad_Scav", label="Sparky", category="Sniper rifle"},
        {record="Items.Preset_Grad_Default", label="SPT32 Grad", category="Sniper rifle"},
        {record="Items.Preset_Metel_AirDrop", label="Taigan", category="Revolver"},
        {record="Items.Preset_Nue_Arasaka_2020", label="Tamayura", category="Pistol"},
        {record="Items.Preset_Tactician_Headsman", label="The Headsman", category="Shotgun"},
        {record="Items.Preset_Shingen_Default", label="TKI-20 Shingen", category="Submachine gun"},
        {record="Items.Preset_Umbra_Collectible", label="Umbra x-MOD2", category="Assault rifle"},
        {record="Items.Preset_Unity_Default", label="Unity", category="Pistol"},
        {record="Items.Preset_Pozhar_Default", label="VST-37 Pozhar", category="Shotgun"},
        {record="Items.Preset_Warden_Default", label="Warden", category="Submachine gun"},
        {record="Items.Preset_Achilles_Nash", label="Widow Maker", category="Precision rifle"},
        {record="Items.Preset_Ashura_Twitch", label="Yasha", category="Sniper rifle"},
        {record="Items.Preset_Dian_Yinglong", label="Yinglong", category="Submachine gun"},
    },
    defaults = {reloadSpeed=1, fireRate=1, recoil=1, spread=1,
        blastRadius=0, blastPush=0, blastLift=0, blastFalloff=1, blastCooldown=0.25},
    presets = {
        {id="stock", label="Stock", values={}},
        {id="fast", label="Rapid fire", values={reloadSpeed=3, fireRate=2, recoil=0.5, spread=0.5}},
        {id="blast", label="Big blast", values={reloadSpeed=3, blastRadius=25, blastPush=15, blastLift=18, blastFalloff=1}},
    },
    ranges = {reloadSpeed={0.25,10},fireRate={0.25,10},recoil={0,3},spread={0,3},
        blastRadius={0,60},blastPush={0,40},blastLift={0,40},blastFalloff={0,4},blastCooldown={0.1,5}},
}
