-- rp_drones -- configuration.
--
-- THIS is the file a server owner edits. `shared/formations.lua` beside it is
-- generated by `tools/make-formations.py` and is overwritten without warning,
-- which is why the shapes and the tuning are not in the same file.
--
-- Everything below is either a place, a size, a duration, a colour or a
-- ceiling. No behaviour lives here.

RpDronesConfig = {
    -- Who may type the command. The platform checks `command.<name>` against
    -- the caller's ACL before the handler runs, so this resource contains no
    -- rights logic of its own -- grant `command.droneshow` to the roles that
    -- should have it.
    command = "droneshow",

    -- One show at a time, and not more often than this. Two shows at once is
    -- two swarms of props on one client, and the client's projection ceiling
    -- is 256 props for EVERYTHING the server owns, not 256 per show.
    cooldownMs = 15000,

    -- =====================================================================
    -- THE SWARM
    -- =====================================================================

    -- Drones in the air. Must equal `RpDronesFormations.count`; the resource
    -- refuses to start otherwise, because a formation with fewer points than
    -- there are drones would leave lit boxes parked beside the picture.
    --
    -- To change it: `python tools/make-formations.py --count N`, then set this
    -- to the same N.
    --
    -- THE COUNT IS THE DIVISOR IN THE BANDWIDTH BUDGET, so what fits depends
    -- entirely on the style. Inside the shipped 64 KB/s slice:
    --
    --   effect / light   24 drones at ~5 Hz; 40 is refused outright
    --   npc              64 drones at 10 Hz, or 24 at the full rate
    --
    -- because an NPC rides the binary protocol at about 100 bytes an update
    -- where a prop or an effect rides a JSON net event at 490 or 555. Start
    -- at 8 whatever the style; the rehearsal show is built for it.
    droneCount = 88,

    -- A second belt, and these days the looser of the two.
    --
    -- THE BANDWIDTH BUDGET REFUSES FIRST: at the shipped 64 KB/s and a 3 Hz
    -- floor, anything past 39 effect drones is turned away before this is
    -- consulted. What this still catches is a show flown with the budget
    -- raised, where the next ceiling is the CLIENT's: it projects at most 256
    -- server-owned props under one session-wide owner, so every prop every
    -- resource on the server owns shares that 256. Past it the 257th drone is
    -- refused per client, silently from the server's point of view, and the
    -- picture comes out with a hole in it on one player's screen.
    -- 120 because the OPEN//77 sign wants 88 and several shows at once share
    -- this ceiling. At 120 npc drones the numbers are: 35 KB in one figure's
    -- burst, 240 client entity slots once the landing lights are counted out
    -- of roughly a thousand, and 120 of the server's 512 NPCs. The bandwidth
    -- gate refuses long before any of those on a streaming style.
    maxDrones = 120,

    drone = {
        -- WHAT A DRONE IS MADE OF.
        --
        --   "npc"     a real flying drone NPC -- a body, rotors, running
        --             lights and an engine rig. The best-looking answer by a
        --             distance, and the newest, so read the `npc` block before
        --             flying it.
        --
        --   "effect"  a looping world VFX at a point. Cheap, proven to hold a
        --             connection, and entirely dependent on finding an asset
        --             that reads as a light rather than as an event -- the
        --             first pass with `race.firework.burst` was reported, not
        --             unfairly, as "it set off fireworks". No colour control:
        --             a VFX is whatever it was authored as.
        --
        --   "light"   a server prop with `kind = "light"`. The palette does
        --             apply. It was the original default and it was WRONG;
        --             read the block under `light` before choosing it.
        style = "effect",

        -- "npc" style --------------------------------------------------
        --
        -- REAL FLYING DRONES, CUT TO SHAPE. Two things are now measured on
        -- screen rather than inferred from the canonical record, and between
        -- them they decide the whole design of this style.
        --
        -- THE HOLD WORKS. Confirmed visually 2026-09-20: a drone spawned at
        -- 10 m with `stage.facing` set to the player's yaw was captured on his
        -- screen -- a real drone body, dark hull, lit eye, hanging in the air
        -- over a Kabuki overpass with nothing under it. A 30 m run reported
        -- drift 0.00 m over thirty seconds with a client projecting it. The
        -- engine does NOT navmesh-project these: the 74.7 m projection in the
        -- platform's research is about humanoid puppets with an AI agent, and
        -- every drone record resolves to an `av_*.ent` VEHICLE template.
        --
        -- THE MORPH DOES NOT. Refuted visually 2026-09-20, in both AI modes.
        -- `npcmove` at 1 Hz over 30 m: 58 sent, 58 accepted, steps up to
        -- 7.79 m, the canonical position changing on 9 reads out of 10 -- and
        -- across four captures with the camera unmoved, building edges
        -- aligning pixel for pixel, THE DRONE DID NOT MOVE. Not by 30 m, not
        -- by a metre. Re-run with a simulation lease (`tasks`, steps up to
        -- 13.79 m) and captured twice more: still the same pixel.
        --
        -- So it is not the 2 m placement deadband and it is not the lease.
        -- A server transform write reaches the canonical record and never
        -- reaches the rendered body. There is no morph on this build.
        --
        -- WHICH LEAVES THE CUT. Spawn the swarm already in formation, hold it,
        -- despawn it, respawn it in the next formation. Many real drone
        -- displays cut through blackout between figures, so this is a look
        -- rather than a consolation -- and it costs NOTHING per tick, only a
        -- spawn and a despawn per drone per figure. That is what puts the
        -- drone count back where the 94-byte state said it could be instead of
        -- where the 256 KB/s clamp forced the particle version.
        --
        -- WHAT IS STILL UNKNOWN: how ragged the cut looks. A spawn is
        -- asynchronous and per client, so the figure fades in at each client's
        -- own projection latency rather than on one frame. The engine waits
        -- for every drone to report a ready body before it starts the hold,
        -- which bounds it, but it cannot make the appearance simultaneous.
        npc = {
            -- Flipping this to true lets `play` fly an npc show anyway. It is
            -- here so that somebody who has MEASURED the four points above to
            -- be wrong on their build can proceed without editing Lua -- not
            -- because it is expected to work.
            allowShow = true,

            record = "Character.q307_zetatech_drone",
            -- Walked by `/droneshow npcprobe next`, most harmless first.
            --
            -- The Bombus family is `Mechanical_NonCombat` and lives in the
            -- base game. `q307_zetatech_drone` and `mq001_nomad_drone_bombus`
            -- additionally ship tagged `Invulnerable` in the catalogue, so
            -- they start harmless rather than being made harmless.
            --
            -- The Wyvern, Griffin and Octant are `Mechanical_Aggressive`
            -- Militech and Zetatech gunships, they are Phantom Liberty assets
            -- (`ep1\...`) so naming one makes the expansion a requirement,
            -- and at 4 m of formation spacing they would overlap anyway. They
            -- are last on the list so they can be looked at once and ruled
            -- out honestly.
            records = {
                "Character.q307_zetatech_drone",
                "Character.mq001_nomad_drone_bombus",
                "Character.Drone_Bombus_Base",
                "Character.BombusFriendly_ow_city_scenes",
                "Character.sq025_delamain_drone_bombus_friendly",
                "Character.Drone_Octant_Base",
                "Character.Drone_Wyvern_Base",
            },

            -- THE APPEARANCE, and the best untried lead on "make the light
            -- come from the drone".
            --
            -- `av_zetatech_bombus__basic.ent` authors NINE appearances, and
            -- the platform's own generated catalogue lists them verbatim. Four
            -- are SURVEILLANCE variants -- and a surveillance drone is the one
            -- the base game flies with a lit sensor head. If one of them is
            -- emissive, the light is the drone's own and every fake glow in
            -- this file becomes unnecessary.
            --
            -- Zero code to try: it is a string on `npcs.create`. `nil` keeps
            -- the template default, which is `..._nanny_drone_blue`.
            --
            -- UNVALIDATED: the names are confirmed valid, what they look like
            -- is not. Nothing in the platform's research carries a screenshot
            -- or a material dump of any of them. `droneshow dronebench` puts
            -- them in a row so one photograph settles it.
            appearance = nil,
            appearances = {
                "zetatech_bombus__basic_surveillance_police_01",
                "zetatech_bombus__basic_surveillance_netwatch_01",
                "zetatech_bombus__basic_surveillance_drone_01",
                "zetatech_bombus__basic_surveillance_service_01",
                "zetatech_bombus__basic_nanny_drone_blue",
                "zetatech_bombus__basic_nanny_drone_violet",
                "zetatech_bombus__basic_nanny_drone_white",
                "zetatech_bombus__basic_delamain_drone_01",
            },

            -- Where `npcprobe` puts it: close enough to stand next to.
            probeStandoff = 25.0,
            -- 30 m, not 2 m. The first probe hovered with drift 0.00 m at
            -- two metres, which a navmesh drop could have produced anyway --
            -- two metres is within the projection's own tolerance. Thirty is
            -- the height a show actually needs, and no navmesh reaches it: if
            -- the drift is still zero here, the body is not being projected to
            -- the ground at all. Measured 2026-09-20.
            probeHeight = 10.0,

            -- When the probe reports, in seconds from the spawn. The first
            -- catches the navmesh projection, the last catches a slow fall.
            probeReportsAt = { 1.0, 3.0, 10.0, 30.0 },

            -- THE VEHICLE-SWEEP GUARD -- a falsified hypothesis, kept anyway.
            --
            -- The drones of a HELD figure were reported flickering in and out
            -- on 2026-09-20, while the server wrote nothing and nothing was
            -- simulating them. Read out of the client source, there was one
            -- path that could repeatedly remove this specific body, and it was
            -- vehicle-specific -- which is what makes a drone different from
            -- every other NPC anyone has spawned here:
            --
            --  * Every drone record resolves to an `av_*.ent`, so the spawned
            --    body is a `vehicleBaseObject`, not an `NPCPuppet`.
            --  * Open77 sweeps everything the entity spawner publishes and
            --    removes vehicles it cannot find in `EntityService`. Its
            --    vehicle branch is armed whenever ambient traffic is off --
            --    the default for any bucket nobody has configured.
            --  * A server-owned NPC only lands in `EntityService` at the END
            --    of its spawn, and the sweep sees it at the START. The sibling
            --    sweep, `WorldSanitizer`, closes exactly that window with a
            --    second check and a 500 ms grace; this one has neither.
            --
            -- IT WAS TESTED AND IT DID NOT FIRE. A full cut show was run with
            -- this guard OFF while the client log was watched across it:
            -- `rejected vanilla vehicle without network identity` appears
            -- ZERO times. Not one rejection. So the race is either not
            -- reachable in this bucket on this build, or it is not what the
            -- owner saw. THE BLINK IS UNEXPLAINED.
            --
            -- The guard is kept because it is cheap, reversible and harmless,
            -- and because the asymmetry between the two sweeps is real and
            -- worth reporting upstream on its own merits. DO NOT BUILD ON IT
            -- and do not treat it as the fix for anything.
            --
            -- What is still known about the blink: it was seen only at 45 m of
            -- standoff, and the geometry moved to 24 m immediately afterwards,
            -- so it has not been observed since. `droneshow npcprobe <record>
            -- <distance>` parks one drone at a stated distance and is the way
            -- to bisect it the next time somebody sees it.
            --
            -- Turning this on tells the bucket ambient traffic is allowed,
            -- which makes the sweep skip the vehicle branch entirely. The side
            -- effect is real: VANILLA TRAFFIC COMES BACK in that bucket for
            -- the duration.
            vehicleSweepGuard = {
                enabled = false,
                -- The crowd and police settings of the bucket are read before
                -- the change and put back afterwards; only traffic is forced.
                -- 2.31 exposes no vehicle density modifier, so traffic is a
                -- switch rather than a fraction -- any value above zero means
                -- vanilla traffic, and the platform reports it as `binary`.
                traffic = 1,
            },

            -- THE LANDING LIGHTS.
            --
            -- Measured 2026-09-20, the owner watching a cut show: "ils font
            -- pas trop de lumiere donc pas tres impressionant dans le ciel".
            -- He is right -- a drone rig's own lights are a couple of small
            -- emissives meant to be seen from a few metres, not across a
            -- square, and the hull is dark.
            --
            -- The fix costs nothing, and it costs nothing for one specific
            -- reason: THE DRONES DO NOT MOVE. A looping effect co-located with
            -- a body that never moves needs no updates at all -- it is spawned
            -- with the figure and retired with it, so a light is just a second
            -- entity on the same 300-bytes-per-figure bill.
            --
            -- `Open77.effects.attach` would bind the effect to the body
            -- instead, which would be tidier and is the right answer the day
            -- these can move. It is not used here: it adds a target-resolution
            -- and incarnation lifecycle to buy following, and nothing follows.
            --
            -- COLOUR COMES FROM THE ASSET, not from a parameter: a VFX is
            -- whatever it was authored as. So a palette colour is mapped to
            -- whichever cooked effect is nearest that colour, and the map is
            -- honest about the ones that have no match. Every path here is
            -- from the 2.31 cooked inventory and unvalidated until the probe
            -- has put it in the sky.
            lights = {
                enabled = true,

                -- A NAMED SET, not a single constant.
                --
                -- Measured 2026-09-20, the owner looking at his own photograph
                -- of the sign: "l'effet bleu en dessous des drones est un peu
                -- bizarre... faut vraiment qu'on ait l'impression que le jeu
                -- de lumiere vienne des drones". The glow sat visibly below
                -- and beside the dark hull -- two objects near each other,
                -- not a lit aircraft. That is a RELATIONSHIP problem, not a
                -- brightness one, and it has two halves: which effect, and
                -- where it sits.
                --
                -- So each light carries its own `offset`. A vehicle entity's
                -- origin is not its visual centre, and every candidate is a
                -- different size, so one global number could never be right
                -- for all of them. Correct a light by editing its own row.
                --
                -- `blue` stays whatever else wins. It was the first thing
                -- that read at all, and the owner asked for it kept as an
                -- option rather than replaced.
                --
                -- Every path is from the 2.31 cooked inventory and is
                -- unvalidated until `droneshow lightbench` has put it in the
                -- sky next to the others.
                set = {
                    blue = {
                        effect = "neon.loot_drop",
                        offset = 0.6,
                        note = "the loot beacon -- the first one that read, and the one in the photograph",
                    },
                    holosphere = {
                        effect = "base\\fx\\devices\\holo_sphere\\d_holo_sphere_distraction.effect",
                        offset = 0.4,
                        note = "a floating holographic ball -- the closest thing 2.31 cooks to a drone body",
                    },
                    glowstick = {
                        effect = "base\\fx\\quest\\sq030\\sq030_glowstick_light.effect",
                        offset = 0.5,
                        note = "a small steady source, authored to be carried in the dark",
                    },
                    lamp = {
                        effect = "base\\fx\\devices\\lights\\d_lights_strong_blinding_light_controller.effect",
                        offset = 0.5,
                        note = "deliberately blinding, which is the point",
                    },
                    candle = {
                        effect = "base\\fx\\quest\\q112\\q112_candle_light.effect",
                        offset = 0.5,
                        note = "a warm flame, from the same parade as the fireworks",
                    },
                    laser_red = {
                        effect = "base\\fx\\devices\\mine_laser\\mine_laser_red_3m.effect",
                        offset = 0.0,
                        note = "a 3 m red column -- the family the AV landing pad letters its sign with",
                    },
                    laser_green = {
                        effect = "base\\fx\\devices\\mine_laser\\mine_laser_green_3m.effect",
                        offset = 0.0,
                        note = "the same column in green",
                    },
                },
                default = "blue",

                -- A step names a `light` directly, or names a `color` and
                -- lands here. Both are kept: the shows were written against
                -- colours before the set existed, and a colour is still the
                -- right word for what a formation wants.
                byColor = {
                    cyan    = "blue",
                    blood   = "laser_red",
                    magenta = "laser_red",
                    acid    = "laser_green",
                    amber   = "candle",
                    white   = "lamp",
                },

                -- Seen from under the show, so it has to reach the ground.
                streamingRadius = 600.0,

                -- `droneshow lightbench` spawns one drone per name in this
                -- list, in a row, at a comfortable distance, and prints the
                -- order. One photograph then identifies every candidate --
                -- which is worth more than a dozen round trips, on the
                -- evidence of the one photograph that settled the sign.
                bench = {
                    "blue", "holosphere", "glowstick", "lamp",
                    "candle", "laser_red", "laser_green",
                },
                benchSpacing = 6.0,
                benchStandoff = 18.0,
                benchHeight = 3.0,
            },

            -- HOW THE SWARM GETS FROM ONE FIGURE TO THE NEXT.
            --
            --   "cut"       hold a figure, black the sky out, cut to the next.
            --               Slow and deliberate, one spawn burst per figure.
            --
            --   "flipbook"  redraw motion pose by pose, no blackout between
            --               them. A figure is cheap and a transform does not
            --               arrive, so the swarm is drawn again rather than
            --               moved. Measured at 2.5 poses a second, which is
            --               motion -- and which the owner watched and called
            --               "saccade, pas smooth du tout: ca bouge frame par
            --               frame". He is right. 2.5 redraws a second will
            --               never read as flight.
            --
            --   "hybrid"    THE ANSWER TO THAT, and it costs nothing new. The
            --               npc style has a BODY and cannot move; the effect
            --               style CAN move -- it is streamed, and the client
            --               repositions a live particle graph in place rather
            --               than restarting it -- and has no body. So each
            --               half does the thing the other cannot:
            --
            --                 lights fly the movement, bodies hold the figure
            --
            --               A movement becomes a smooth stream of effect
            --               drones from pose A to pose B; on arrival the
            --               lights hand over to real bodies for the hold, and
            --               hand back when the next movement starts. One
            --               crossfade per figure, and both halves already
            --               existed in this file.
            --
            -- They are different instruments and both are kept: a hold-and-cut
            -- show and a flip-book look nothing alike.
            --
            -- `/droneshow choreo cut|flipbook|hybrid` switches it and
            -- the choice survives a reload. `sequence` is accepted as a
            -- synonym for `flipbook`: it was called that for an afternoon,
            -- while a since-retracted measurement said it was a slideshow.
            choreography = "cut",

            -- THE FLIP-BOOK DRIVER.
            --
            -- A drone cannot be moved -- a server transform reaches the
            -- canonical record and never the rendered body, measured on camera
            -- -- but a whole FIGURE costs only 300 bytes a drone. So motion is
            -- not written, it is REDRAWN: interpolate between two formations,
            -- cut each intermediate pose, hold it just long enough for the next
            -- to replace it. That is a flip-book.
            --
            -- MEASURED 2026-09-20, 8 drones at 24 m, from the driver's own
            -- readiness counter, three movements per run:
            --
            --   250 ms   ABANDONED after 4 frames, nothing ready
            --   400 ms   10 frames per movement, 8 of 8 ready on every one
            --   600 ms   7 frames per movement, 8 of 8
            --
            -- So 400 ms holds, on every movement of a three-movement show.
            -- That is two and a half poses a second, and it is motion.
            --
            -- A CAVEAT THE NEXT PERSON MUST HAVE. An earlier run of this same
            -- counter read 0 of 8 at 300 ms and stayed there for fifty frames,
            -- and that number was WRONG -- an artefact of a defect in this
            -- resource, not a property of the platform. Frames were being
            -- issued faster than a spawn could land, so roughly four spawns
            -- per drone were in flight at once and the counter was reading a
            -- queue this resource had flooded. `abortAfterEmptyFrames` below
            -- is the fix, and it is what made the clean bisection possible.
            -- The lesson is not about drones: a self-measuring driver can
            -- measure its own bug and report it as physics.
            --
            -- WHERE THE ~400 ms GOES, decomposed from the platform's source.
            -- It is not one slow thing, and most of it does not scale with
            -- hardware:
            --
            --   33 ms   one server tick before the create is even SENT --
            --           `Create` fires into an empty viewer set, so the packet
            --           leaves on the next interest reconcile
            --   17 ms   a client frame to drain it
            --   17 ms   at least one more frame: the entity stub is created
            --           off the game thread and parked for the next one
            --  250 ms   THE READINESS SETTLE. A fixed wait between the body
            --           attaching and the client reporting it ready. Not a
            --           tick, not tunable, paid on every machine.
            --   33 ms   one more server tick for this resource's own poll
            --    4 ms   two 2 ms network-worker polls
            --  ------
            --  ~350 ms  of fixed cost, plus round trip, plus the engine
            --           streaming the vehicle entity -- which has no deadline
            --           in the code at all, only a per-frame "is it there yet".
            --
            -- TWO CONSEQUENCES FOR A REAL SERVER, and they point opposite ways.
            -- The 250 ms settle and the two 30 Hz server ticks are constants,
            -- so a faster machine will not beat 400 ms. But the round trip is
            -- NOT a constant: this was measured on loopback, and a server with
            -- 60 ms of ping to its players needs that much again. Budget
            -- 400 ms + your RTT, and re-bisect on the machine that matters.
            -- The streaming term also grows with the swarm: eight vehicle
            -- entities at once is not sixty-four.
            -- The crossfade, for the hybrid driver.
            hybrid = {
                -- Milliseconds the lights and the bodies are BOTH up, at each
                -- end of a movement. A hard swap would flash: the lights would
                -- be gone for however long a body takes to stream, which is
                -- the 400 ms this file spends the rest of its time measuring.
                -- An overlap costs one extra figure's worth of entities for
                -- that moment and buys a seam nobody sees.
                overlapMs = 500,
                -- What the flying half is made of. It is a normal effect-style
                -- drone, so it uses `drone.effect` and everything the effect
                -- style already knows -- including that nobody has yet
                -- confirmed which of the candidates reads as a light at this
                -- distance. Probe first.
                useConfiguredEffect = true,
            },

            sequence = {
                -- The measured frame. A floor, not a target: the bandwidth
                -- budget below can still make it slower.
                frameMs = 400,
                -- Nothing under this is accepted, from config or from
                -- `droneshow frame`. The fixed costs above already come to
                -- ~350 ms before a byte of mesh moves, so a shorter frame
                -- cannot work -- and it is not merely useless. A spawn already
                -- in flight is NOT cancelled when the next frame despawns it:
                -- the cancel sets a flag and the engine still fully streams,
                -- instantiates and then destroys the body. Eight drones at
                -- 300 ms was about twenty-seven complete vehicle
                -- spawn-and-destroy cycles a second, for nothing visible.
                --
                -- 300 rather than 350 so the boundary itself can still be
                -- probed; the abandon guard makes that cost four frames.
                absoluteFloorMs = 300,
                -- The budget's own ceiling, far above the measured floor. It
                -- exists only so a large swarm cannot quietly stretch the
                -- frame into minutes.
                maxFrameMs = 3000,
                reportReadiness = true,
                -- Redrawing faster than a spawn can land floods the client's
                -- bounded request table and makes the readiness counter lie.
                -- This many frames in a row with NOTHING ready and the
                -- movement is abandoned, which is also what makes a bisection
                -- run safe to type.
                abortAfterEmptyFrames = 4,
                -- Whether the landing lights are redrawn on every frame of a
                -- movement, or only on the pose it lands on.
                --
                -- false HALVES the entity churn -- a lit figure is a body and
                -- a light per point. At 400 ms the swarm going dark to move
                -- and lighting up when it arrives is a deliberate look; turn
                -- it on if it reads as a dropout instead.
                lightsWhileMoving = false,
            },

            -- THE CUT. How long the sky stays empty between two figures.
            --
            -- Long enough to read as a deliberate cut rather than as a
            -- stutter, and long enough for the despawn to have landed on every
            -- client before the next spawn starts arriving. 1.2 s is about one
            -- slow breath; under 600 ms it starts to look like a glitch.
            blackoutMs = 1200,

            -- What a whole figure costs one viewer, in bytes per drone.
            -- MEASURED from the encoders rather than guessed:
            --   NpcCreate  94 + record (28 for a `Character.*` drone) = 122
            --   NpcState   70
            --   NpcRemove  17
            -- each under a 24-byte header, so 146 + 94 + 41 = 281. 300 rounds
            -- it up. Per drone, per FIGURE -- not per second, and not per
            -- tick, which is the entire point of cutting instead of morphing.
            bytesPerFigure = 300,

            -- `droneshow npcmove` -- the movement instrument.
            --
            -- It flies ONE drone back and forth and measures what actually
            -- happened, because the thing standing between a working static
            -- drone and a working show is whether a server-written transform
            -- reaches the body at all.
            --
            -- WHAT IT IS LOOKING FOR. A server `setTransform` bumps the NPC's
            -- revision, the client compares the new canonical point against
            -- where the body is, and arms a placement ONLY IF THEY DIFFER BY
            -- MORE THAN TWO METRES. An armed placement then issues an
            -- `AI::TeleportCommand` every 300 ms until the body is within two
            -- metres, up to twelve times. So the prediction is sharp:
            --
            --   steps under 2 m   swallowed entirely, the body never moves
            --   steps over 2 m    coarse teleports, at best every 300 ms
            --
            -- `stepMetres` in the report is the number to watch against that
            -- 2 m line. The defaults deliberately sweep both sides of it.
            move = {
                rate = 2.0,
                metres = 10.0,
                -- "horizontal" sweeps across the viewer, "vertical" up and
                -- down. Try both: a non-authority client computes an NPC's
                -- speed as hypot(vx, vy) and idles the body below 0.15 m/s,
                -- so vertical motion has its own way of going missing.
                axis = "horizontal",
                -- "frozen" is what a show would use. "tasks" grants a
                -- simulation lease, which is the ONLY way the reported
                -- position becomes an observation rather than an echo -- see
                -- the note on inertness in the README.
                mode = "frozen",
                reportsAt = { 1.0, 3.0, 10.0, 30.0 },
            },

            -- What one `setTransform` costs on the wire, per viewer. MEASURED
            -- from the encoder rather than guessed: `Encode(NpcState)` builds
            -- `70 + appearance + loadout` bytes, both strings are empty here
            -- and their two-byte length prefixes are already inside the 70, so
            -- the payload is exactly 70 under a 24-byte header.
            bytesPerState = 94,

            -- "transform" streams canonical positions (see point 3 above);
            -- "task" hands out destinations (see point 2). Both are wired so
            -- that a probe can demonstrate the failure rather than assert it.
            movement = "transform",
            task = {
                speed = "walk",
                acceptanceRadius = 2.0,
                timeoutMs = 60000,
            },

            -- A created NPC is an id at once and a body in the world later,
            -- asynchronously, per client. A show behind `allowShow` waits for
            -- every drone to report a ready projection before it starts, or
            -- it would fly a formation half of which is not there yet.
            readyTimeoutMs = 20000,

            -- Roughly how wide the rig is, metres. Not enforced -- it is
            -- logged next to the formation's actual nearest-neighbour spacing
            -- so that "the drones are inside each other" is a number before it
            -- is a screenshot. A Bombus is small; a Wyvern is not.
            bodyMetres = 2.5,
        },

        -- "effect" style -----------------------------------------------
        --
        -- WHICH EFFECT IS THE OPEN QUESTION of this resource, and it is not
        -- one a config file can answer: every candidate below is an asset
        -- authored for some other purpose, and how each reads as a point of
        -- light at 45 m against a night sky has to be looked at.
        --
        -- `/droneshow probe` exists for exactly that. It hangs ONE drone in
        -- front of you and does not move it, so trying all of these costs one
        -- entity and no bandwidth at all. `/droneshow probe next` walks the
        -- list below; `/droneshow probe off` takes it down.
        effect = "base\\fx\\devices\\holo_sphere\\d_holo_sphere_distraction.effect",
        -- The two controls at the end of the list are there to be compared
        -- against, not chosen: `neon.loot_drop` was photographed as
        -- "unmistakable at 5 m" and "at most a faint speck" at 20 m, so if it
        -- reads at 45 m the stage is too close; `race.firework.burst` is the
        -- one that set off fireworks.
        probes = {
            -- Ordered by what is most likely to read as a POINT rather than
            -- as an event. The first list was burst effects, and the first
            -- flight proved the point: eight bursts in formation look like
            -- fireworks, not like drones (measured in game 2026-09-20, the
            -- owner's words: "ca a mis des feux d'artifices"). A drone wants
            -- a steady source that hangs there, so these are lamps, sticks
            -- and spheres. Every one comes from the cooked inventory and is
            -- unvalidated until the probe puts it in the sky.
            -- a floating holographic ball -- the closest thing 2.31 cooks to a drone body
            "base\\fx\\devices\\holo_sphere\\d_holo_sphere_distraction.effect",
            -- a glowstick: a small steady source, authored to be carried in the dark
            "base\\fx\\quest\\sq030\\sq030_glowstick_light.effect",
            -- a deliberately blinding lamp -- the brightest candidate in the inventory
            "base\\fx\\devices\\lights\\d_lights_strong_blinding_light_controller.effect",
            -- a candle flame, from the same parade as the fireworks
            "base\\fx\\quest\\q112\\q112_candle_light.effect",
            -- a blinking phone light -- a drone strobe, if it reads
            "base\\fx\\quest\\minor_quests\\mq028\\cellphone_flashing_light.effect",
            -- The controls: a laser dot, and the burst that started this.
            "laser.mine",
            "neon.loot_drop",
            "race.firework.burst",
        },

        -- "light" style ------------------------------------------------
        --
        -- READ THIS BEFORE SWITCHING TO IT. A `kind = "light"` drone was the
        -- first design, it was flown in game, and NOBODY COULD SEE IT. Two
        -- independent reasons, both confirmed in the platform's own source:
        --
        --  1. THE HOST IS CULLED AT 50 METRES. The light host entity is
        --     cloned from a loot crate and keeps that crate's authored
        --     `autoHideDistance = 50`; the asset build raises it to 200 on
        --     every MESH host and never touches the light host. The renderer
        --     therefore hides the light component past 50 m no matter what
        --     `streamingRadius` says. That is an asset defect, not something
        --     this resource can patch -- `maxVisibleDistance` below turns it
        --     into a refusal instead of an invisible show.
        --
        --  2. A POINT LIGHT IN EMPTY AIR DRAWS NOTHING. It has no body: it
        --     only illuminates other geometry within `radius`. With
        --     `scaleVolFog` and `useInFog` both 0 on the host there is no
        --     airborne halo either. Every positive light result in this
        --     platform's research is light landing on a wall or on steps.
        --
        -- So the light style is not a drone. What it IS, with the radius set
        -- wide enough to reach the ground below, is a formation of moving
        -- coloured pools on the terrain -- a real effect, and a good one, but
        -- a different show. It is kept for that, and for close quarters.
        --
        -- `model` is dead config for a light and is not read: the client
        -- always spawns its one light host whatever the model names.
        light = {
            -- 0-10000. 850 is the brightest value anything in this platform
            -- ships (a Cordon street lamp); the admin default is 20, and a
            -- measured 140 was "bright in a room and nothing on a street".
            intensity = 850.0,
            -- Falloff radius in metres, 0.1-500, HARD-CLIPPED at that
            -- distance. The original 10 m was the second bug: a drone 50 m up
            -- with a 10 m radius has nothing inside its falloff to light.
            -- 120 reaches the ground from the stage, which is the only way
            -- this style produces a visible pixel.
            radius = 120.0,
            -- Point, not spot. `spot` is the one light field that cannot be
            -- changed without respawning the entity, so the show never
            -- touches it.
            spot = false,
            -- Refuse the show when any drone would sit further than this from
            -- the anchor, because past the host's baked 50 m the renderer
            -- culls it and the show is silently invisible. 45 leaves margin.
            maxVisibleDistance = 45.0,
        },
    },

    -- =====================================================================
    -- THE STAGE -- where the picture hangs, in metres, relative to the
    -- anchor point (the operator, or the coordinates the console named).
    -- =====================================================================
    --
    -- The picture is a flat plane standing in the sky, and it ALWAYS FACES
    -- THE ANCHOR: the engine takes the horizontal direction from the anchor
    -- to the stage centre as the plane's normal. So `facing` only decides
    -- which way the show is from you, never whether you see it edge-on.
    stage = {
        -- Yaw in degrees, same convention as a prop's `yaw`: 0 puts the show
        -- along +Y. Override per cast with `/droneshow <show> <yaw>`.
        facing = 0.00,
        -- HOW FAR THE PICTURE HANGS, AND WHY IT KEPT MOVING CLOSER.
        --
        -- It started at 80 m out and 50 m up, on the strength of a firework
        -- measurement: 25-45 m "big in frame and clearly in the sky", 55-95 m
        -- "distant sparks". THAT NOTE DOES NOT TRANSFER, and this is the
        -- correction. A firework shell is a burst tens of metres across; a
        -- drone rig is about 2.5 m of dark hull. The owner's verdict on the
        -- first npc show was the whole lesson in one line: "faut les afficher
        -- bien plus proche de nous parce qu'ils sont petit".
        --
        -- 24 m out and 16 m up is a drone show's real geometry: WATCHED FROM
        -- UNDERNEATH, filling the view rather than sitting in the distance. A
        -- 22 m figure at 24 m spans about 49 degrees, and the drones sit
        -- between 24 and 36 m from the viewer -- where a 2.5 m body is
        -- something you can see rather than something you can find.
        --
        -- The 25-45 m band is still right FOR FIREWORKS. It is in this file's
        -- history because it was the only measurement anyone had; it is not a
        -- rule about drones and should not be applied as one.
        --
        -- Bringing the stage in also shortens every flight path, which is what
        -- pays for the update rate on the streaming styles.
        standoff = 24.0,
        -- Centre height above the anchor. The picture is centred here, so its
        -- top edge is at 47 m and its bottom at 13 m -- the whole figure
        -- inside the measured window.
        altitude = 16.0,
        -- What `u = -1 .. 1` and `v = -1 .. 1` span. Keep the two equal: every
        -- shipped shape is normalised into a square, so an unequal pair turns
        -- the ring into an ellipse and the 77 into a slanted 77.
        --
        -- 34 m at 45 m of standoff is 41 degrees across -- it fills the view
        -- without having to be looked around.
        width = 22.0,
        height = 22.0,
    },

    -- The launch pad: a horizontal lattice on the ground.
    --
    -- NOTHING SHIPPED USES IT ANY MORE. A launch from the pad to the stage is
    -- a 75 m flight for every drone at once, which was about 60% of the whole
    -- show's bandwidth and all of its speed problem -- and the byte budget
    -- below has to pay for it out of the same slice as the figures. The
    -- shipped shows now reveal the swarm already in formation, dark, and
    -- ignite it (`lit = false` on the first step), which costs one message
    -- per drone instead of ninety.
    --
    -- The machinery is kept because a server on a fat link may want a real
    -- launch, and because it is the honest place to put `place = "pad"`.
    pad = {
        altitude = 2.0,
        width = 22.0,
        -- The pad lies flat, so its "height" is depth along the ground.
        depth = 16.0,
    },

    -- A drone is meant to be seen from across a district. The 120 m default
    -- would stream it out while the audience is still watching.
    -- Range 10-2000; hysteresis is extra distance before it streams out.
    streamingRadius = 900.0,
    streamingHysteresis = 150.0,

    -- =====================================================================
    -- THE BANDWIDTH BUDGET, AND THE CLOCK IT BUYS
    -- =====================================================================
    --
    -- READ THIS BLOCK BEFORE CHANGING ANY OF IT. It is the difference between
    -- a light show and a disconnected player, and that is not a figure of
    -- speech: the first build of this resource dropped its own audience with
    -- `send_failed:LimitExceeded` eight seconds into the opening morph.
    --
    -- THE CEILING IS 256 KB/s PER CONNECTION. GameNetworkingSockets clamps
    -- every connection's send rate there by default and returns
    -- `LimitExceeded` -- which the transport turns into a DISCONNECT, not a
    -- dropped packet -- once 512 KB has queued behind the clamp. That ceiling
    -- is shared with everything else the server sends that player: position
    -- snapshots for every peer, vehicles, NPCs, chat. A drone show is
    -- decoration, so it gets a slice and not the link.
    --
    -- The rate is therefore NOT configured. It is DERIVED from the byte
    -- budget below, and the engine refuses a show it cannot fly inside it.
    clock = {
        -- The slice, in bytes per second, per viewer. 65,536 is a quarter of
        -- the 256 KB/s clamp: it leaves about 190 KB/s for the replication
        -- the server actually exists to do, which at the measured ~5.2 KB/s
        -- per peer is roughly 36 other players.
        --
        -- THIS IS THE ONE NUMBER TO RAISE on a small or private server, and
        -- the one to lower on a full one. Raising it past ~200,000 will drop
        -- clients; past 262,144 it is guaranteed to. A server that genuinely
        -- needs more can raise the clamp itself with the transport's
        -- OP77_GNS_SEND_RATE_BYTES / OP77_GNS_SEND_BUFFER_BYTES overrides,
        -- which this resource cannot see and does not assume.
        maxBytesPerSecondPerViewer = 65536,

        -- What one drone update actually costs on the wire, per style,
        -- MEASURED by serialising the exact record the server sends
        -- (`ServerApplication.ToNetwork`) with this resource's own field
        -- values, plus 24 bytes of packet header, 12 of net-event framing and
        -- the event name. A prop carries its model, scale, physics, streaming
        -- distances and whole light table on every position change; an effect
        -- carries both spellings of its name plus timestamps. Neither is
        -- something this resource can trim.
        --
        -- These are the divisor in the rate calculation. If the platform's
        -- serialiser changes, re-measure them -- an understated figure here
        -- is how the show gets back over the clamp.
        bytesPerUpdate = {
            light = 490,
            effect = 555,
            -- An NPC is a different channel entirely: its own BINARY message
            -- kinds rather than a JSON net event carrying the whole record.
            -- `NpcMotion` -- the authority client's 10 Hz report, relayed to
            -- every other viewer -- is a fixed 71-byte payload under a
            -- 24-byte header, so 95 bytes. A server `setTransform` instead
            -- emits `NpcState`, 70 bytes plus the appearance and loadout
            -- strings, which are empty here.
            --
            -- 100 rounds that up. It is six times cheaper than an effect, and
            -- it is entirely academic until the platform grows a movement
            -- command that leaves the ground -- see the `npc` block above.
            npc = 100,
        },

        -- The rate the show would LIKE, per drone, per second. It is a
        -- ceiling on the derived rate, never a floor: the budget wins.
        -- The server's Lua VMs tick once per server tick (30 Hz by default),
        -- so 30 is the hard maximum whatever is written here.
        updateHz = 8,

        -- Below this the swarm is a slideshow rather than a show, so the
        -- engine REFUSES to fly rather than flying badly, and the refusal
        -- says how many drones would fit.
        minUpdateHz = 3.0,

        -- How far a drone may jump between two updates, in metres. This, not
        -- a speed, is the thing worth configuring, and it is per style for one
        -- reason: WHETHER THE CLIENT INTERPOLATES.
        --
        -- A prop and an effect do not interpolate. The position is written
        -- with a hard engine call, so the drone teleports from one update to
        -- the next and the step is exactly what the eye sees. 0.6 m at 45 m of
        -- standoff is about three quarters of a degree, which reads as flight.
        --
        -- An NPC does. Non-owner clients interpolate authoritative NPC motion
        -- toward the canonical transform, so the update rate stops being the
        -- frame rate and a much coarser step still looks smooth. 2.5 m is a
        -- guess in the right direction, not a measurement -- if npc drones
        -- visibly snap between positions, lower it; if they visibly lag the
        -- music, raise it.
        --
        -- The engine derives the speed limit from this
        -- (`maxSpeed = maxStepMetres x the derived rate`) and STRETCHES any
        -- morph that would exceed it.
        maxStepMetres = {
            light = 0.6,
            effect = 0.6,
            npc = 2.5,
        },

        -- Dead band, metres. A drone whose new position is closer than this
        -- to the last one SENT is not sent at all. This is not a micro-
        -- optimisation: the server has no equality check, so without it a
        -- formation being held would keep paying full price for standing
        -- still. With it, a hold costs nothing.
        moveEpsilon = 0.05,

        -- Coordinates are rounded to this many decimals before they are sent.
        -- A full round-trip double is up to 19 characters and three of them
        -- ride in every update; two decimals is 1 cm of precision, which is
        -- invisible at any distance this show is watched from, and it takes
        -- 7% off every single message.
        positionDecimals = 2,

        -- Consecutive failed transform writes before the show gives up and
        -- takes the swarm down. A world that went away mid-show should end
        -- with an empty sky, not with abandoned props.
        failureBudget = 24,
    },

    -- =====================================================================
    -- COLOURS -- linear, each channel 0-1. Only the "light" style uses them.
    -- =====================================================================
    --
    -- The keys really are 1/2/3 as red/green/blue here and become x/y/z at the
    -- API boundary; the native rejects an { r, g, b } table outright.
    --
    -- A COLOUR CHANGE IS A CUT, NEVER A FADE. Writing a light's colour
    -- disables its component for one frame before re-enabling it, so an
    -- animated colour strobes. The engine therefore changes colour only at a
    -- formation boundary, where the one-frame blink reads as a flash.
    palette = {
        white   = { 1.00, 1.00, 1.00 }, -- #FFFFFF
        cyan    = { 0.10, 0.85, 1.00 }, -- the platform's own accent
        magenta = { 1.00, 0.10, 0.60 },
        amber   = { 1.00, 0.62, 0.05 },
        acid    = { 0.65, 1.00, 0.10 },
        blood   = { 1.00, 0.08, 0.08 },
    },
    defaultColor = "cyan",

    -- =====================================================================
    -- LIVE MOTION: THE CONCURRENCY BUDGET
    -- =====================================================================
    --
    -- The owner asked for drones that advance, retreat, flip, and for the sign
    -- to draw itself progressively rather than appear whole -- and said the
    -- constraint himself: "faut plus de frame pour que ca soit LIVE".
    --
    -- HE IS RIGHT, AND THE WAY OUT IS NOT MORE BANDWIDTH. It is to stop
    -- assuming the whole swarm moves at once. An effect drone that is NOT
    -- moving costs nothing at all -- nothing is written for it -- so the bill
    -- is `drones IN FLIGHT x rate x bytes`, not `swarm x rate x bytes`. A sign
    -- that draws itself has a moving FRONT and a static tail, and only the
    -- front is paid for.
    --
    -- Computed against the measured 555 bytes per effect update and the
    -- 64 KB/s slice:
    --
    --   if EVERY drone moves          8 -> 14.8 Hz    24 -> 4.9 Hz
    --                                48 ->  2.5 Hz    88 -> 1.3 Hz
    --
    --   staggered, drones in flight   4 Hz -> 29     10 Hz -> 11
    --   at once, ANY swarm size       6 Hz -> 19     12 Hz ->  9
    --                                 8 Hz -> 14     15 Hz ->  7
    --
    -- So the 88-drone sign cannot be animated as a swarm at any useful rate --
    -- 1.3 Hz -- and CAN be drawn stroke by stroke at 8 Hz with a front of 14,
    -- for 61 KB/s. Bounding concurrency does not merely make live motion
    -- affordable; it makes it cheaper than the whole-figure redraw it replaces.
    motion = {
        -- The rate a moving drone is streamed at. The mover cap below is
        -- derived from it, so raising this lowers how many may fly at once.
        rateHz = 8,
        -- A hard ceiling on concurrent movers, on top of whatever the budget
        -- allows. The budget is about the link; this is about the eye -- a
        -- front wider than about a fifth of the swarm stops reading as a front.
        maxMovers = 16,
    },

    -- =====================================================================
    -- THE SHOWS
    -- =====================================================================
    --
    -- A show is a list of STEPS, and a step is one pose plus the flight into
    -- it:
    --
    --   formation  a key of `RpDronesFormations.shapes`
    --   place      "stage" (the vertical picture) or "pad" (the flat lattice)
    --   morph      milliseconds of flight from the previous pose. 0 means
    --              "stay where you are", which is how a colour cut or an
    --              ignition gets its own beat.
    --   hold       milliseconds to stand still once the pose is reached.
    --              A hold costs no bandwidth at all -- see `moveEpsilon`.
    --   color      a key of `palette`, applied on arrival
    --   lit        false hangs the drones dark. Default true.
    --   blackout   npc style only: milliseconds of empty sky before this
    --              figure appears. Defaults to `drone.npc.blackoutMs`.
    --
    -- A SHOW MAY ALSO CARRY ITS OWN `stage`, overriding any of `standoff`,
    -- `altitude`, `width` and `height` for that show only. A sign is not a
    -- ring: `OPEN//77` needs to be three times wider than it is tall and to
    -- hang far enough back to fit in the frame, and forcing the global stage
    -- to suit it would ruin every other show.
    --
    -- THE NPC STYLE READS THE SAME LIST DIFFERENTLY. It cannot morph, so it
    -- ignores `morph` entirely and cuts instead: despawn, blackout, respawn in
    -- the next formation. Every show below therefore works under either style,
    -- and reads as a different thing in each.
    --
    -- Durations are written as the flight and the pause, not as absolute
    -- offsets like the fireworks cues, because a morph that gets stretched by
    -- the derived speed limit would push every later offset out of step.
    --
    -- THE MORPHS BELOW ARE AT THEIR MINIMUMS for 24 effect drones inside the
    -- byte budget: ring to heart needs 14.2 s, heart to 77 needs 11.7 s, and
    -- 77 back to ring needs 18.2 s, because the longest single path in each
    -- is 28, 23 and 36 metres and the speed limit is 2.95 m/s. Shorten one
    -- and the engine stretches it back and logs that it did. Raise
    -- `maxBytesPerSecondPerViewer`, or lower `droneCount`, to go faster.
    shows = {
        -- The full performance: ignite, three figures, go dark. 68 seconds.
        --
        -- The first two steps are the reveal. The swarm is spawned already in
        -- the ring, dark, held for two seconds so it has streamed in on every
        -- client, and then lit -- one message per drone. That is the whole
        -- launch, and it replaced a 75 m climb from a pad that cost more
        -- bandwidth than the three figures put together.
        open77 = {
            { formation = "ring",          place = "stage", morph = 0,     hold = 2000, color = "cyan",    lit = false },
            { formation = "ring",          place = "stage", morph = 0,     hold = 3000, color = "cyan" },
            { formation = "heart",         place = "stage", morph = 15000, hold = 4000, color = "magenta" },
            { formation = "seventy_seven", place = "stage", morph = 12000, hold = 7000, color = "amber" },
            { formation = "ring",          place = "stage", morph = 19000, hold = 2500, color = "cyan" },
            { formation = "ring",          place = "stage", morph = 0,     hold = 1200, color = "cyan",    lit = false },
        },

        -- One figure. 29 seconds, for a finish line or a toast, where nobody
        -- is going to watch for a minute.
        salute = {
            { formation = "ring",          place = "stage", morph = 0,     hold = 1500, color = "amber", lit = false },
            { formation = "ring",          place = "stage", morph = 0,     hold = 1500, color = "amber" },
            { formation = "seventy_seven", place = "stage", morph = 19000, hold = 6000, color = "amber" },
            { formation = "seventy_seven", place = "stage", morph = 0,     hold = 1000, color = "amber", lit = false },
        },

        -- Just the heart, and it stays up long enough to be photographed. The
        -- fourth step is a colour cut with no flight: morph 0, so the swarm
        -- stands still and only changes colour. 54 seconds.
        heart = {
            { formation = "ring",  place = "stage", morph = 0,     hold = 1500,  color = "magenta", lit = false },
            { formation = "ring",  place = "stage", morph = 0,     hold = 2000,  color = "magenta" },
            { formation = "heart", place = "stage", morph = 15000, hold = 20000, color = "magenta" },
            { formation = "heart", place = "stage", morph = 0,     hold = 14000, color = "blood" },
            { formation = "heart", place = "stage", morph = 0,     hold = 1200,  color = "blood",   lit = false },
        },

        -- THE SIGN DRAWING ITSELF. The same letters, revealed stroke by
        -- stroke instead of appearing whole.
        --
        -- `reveal` is a per-step field, and it is the CHEAP half of live
        -- motion: the drones appear along the stroke in order rather than all
        -- at once, at a bounded rate, so the sign writes itself. It costs one
        -- create per drone spread over the reveal -- 88 drones over 8 seconds
        -- is 11 creates a second, about 6 KB/s, a tenth of the slice.
        --
        -- It works WHETHER OR NOT a streamed effect glides, because nothing
        -- moves: each drone is placed once, where it belongs. The richer
        -- version, where each drone also flies in from off-stroke, is designed
        -- and not built -- it depends on the glide, and the glide is still
        -- unmeasured. See the README.
        signdraw = {
            stage = { standoff = 40.0, altitude = 26.0, width = 32.0, height = 24.0 },
            { formation = "sign_open77_stacked", place = "stage", morph = 0,
              hold = 14000, color = "cyan", reveal = 8000 },
        },

        -- THE SIGN. OPEN//77 written in the sky, on two lines.
        --
        -- IT NEEDS 88 DRONES, and that is not a round number chosen for
        -- comfort. A sign is a length of stroke, and the drones have to sit
        -- along it close enough to read as a line rather than as dots -- about
        -- two metres apart, given a rig that is roughly two and a half metres
        -- across. Fewer drones and the same sign has gaps in the letters; more
        -- and the sign has to grow to keep the spacing, until it no longer
        -- fits in the frame.
        --
        -- Measured off the generated point sets, at a 2 m mean gap:
        --
        --   count   stacked sign      one line
        --      48    22 x 17 m         42 x  7 m
        --      64    26 x 19 m         47 x  8 m
        --      88    32 x 24 m         60 x 10 m
        --     120    44 x 33 m         81 x 14 m
        --
        -- 88 on two lines is the one that works: a 32 x 24 m sign fits the
        -- frame at 40 m and the letters are a third of its height. The ONE
        -- LINE layout is in the generator too and is not recommended -- at the
        -- same legibility it is 60 m wide and 10 m tall, which needs 65 m of
        -- standoff, and at 65 m a 2.5 m drone is a speck again.
        --
        -- 48 and 120 also put two drones within a metre of each other at a
        -- stroke junction, where 88 keeps them furthest apart. The generator
        -- refuses outright if any pair lands closer than a hair, but "nearly
        -- stacked" is still wasted drones, so prefer 88.
        --
        -- AND THE HULLS DO OVERLAP AT JUNCTIONS. Measured in game: 0.61 m
        -- between the closest pair against a rig about 2.5 m across. THIS IS
        -- BY DESIGN for a sign, and the photograph is the argument -- the LIGHT
        -- is the mark, the light is much smaller than the body, and the letters
        -- read. Spacing the hulls properly would need a sign more than three
        -- times wider, which would not fit the frame at any standoff where a
        -- 2.5 m drone is still visible.
        --
        -- It is stated here rather than left to be rediscovered, and the show's
        -- own log line says `UNDER THE RIG` when it happens rather than printing
        -- two numbers to compare.
        --
        -- Cost: 26 KB per figure per viewer, 88 of the server's 512 NPCs, and
        -- 176 of the client's ~1,024 entity slots once the landing lights are
        -- counted. The untested part is eighty-eight vehicle entities
        -- streaming at once -- watch the readiness line.
        --
        -- A CUT show, not a flip-book: a sign wants to appear, hold long
        -- enough to be photographed, and go.
        sign = {
            stage = { standoff = 40.0, altitude = 26.0, width = 32.0, height = 24.0 },
            { formation = "sign_open77_stacked", place = "stage", morph = 0, hold = 14000, color = "cyan" },
        },

        -- THE PARADE, for the flip-book driver. Four poses and three
        -- movements, about 24 seconds.
        --
        -- NOT called `choreo`, and that is not a style choice: `choreo` is a
        -- SUBCOMMAND, and a show with the same name was swallowed by it --
        -- `droneshow choreo <x> <y> <z>` silently set the driver and answered
        -- "Choreography is cut or sequence" instead of playing anything. The
        -- resource now refuses to arm if any show name collides with a
        -- subcommand, so the next one cannot get as far as a console.
        --
        -- The morphs are SHORT compared with the other shows on purpose. Those
        -- durations were sized by the streaming styles' speed limit -- how far
        -- a drone may jump between two updates -- and the flip-book driver
        -- has no such limit, because it is not interpolating anything. So a
        -- movement here is as long as it should look, not as long as the
        -- bandwidth makes it.
        --
        -- Under the cut driver this is the same show with the movements
        -- replaced by blackouts, which is a perfectly good show and a
        -- completely different one. Under a STREAMING style its morphs are
        -- too short for the speed limit and the engine stretches them, saying
        -- so in the log -- that is the gate working, not a misconfiguration.
        -- The short durations are kept because this show is for the
        -- flip-book driver.
        parade = {
            { formation = "ring",          place = "stage", morph = 0,    hold = 3000, color = "cyan" },
            { formation = "heart",         place = "stage", morph = 4000, hold = 2500, color = "magenta" },
            { formation = "seventy_seven", place = "stage", morph = 4000, hold = 4000, color = "amber" },
            { formation = "ring",          place = "stage", morph = 4000, hold = 2000, color = "cyan" },
        },

        -- THE CUT REHEARSAL -- two figures, for the npc style, at 8 drones.
        -- Ring, cut, 77, cut, gone. Twenty seconds, two spawn bursts, and
        -- nothing at all between them.
        --
        -- Under the effect or light style this is a morph show like any
        -- other; under npc it is the smallest thing that demonstrates a cut.
        cut = {
            { formation = "ring",          place = "stage", morph = 0, hold = 6000, color = "cyan" },
            { formation = "seventy_seven", place = "stage", morph = 0, hold = 8000, color = "amber" },
        },

        -- THE REHEARSAL, and the one to fly first, every time. Two poses and
        -- one morph: it exercises the whole pipeline -- spawn dark, ignite,
        -- fly, recolour, go dark, recall -- in half a minute.
        --
        -- Fly it at `droneCount = 8` for a first run on a live session. Eight
        -- drones cost a third of what twenty-four do and buy three times the
        -- update rate, so it is both the cheapest thing that can go wrong and
        -- the smoothest thing to look at. Regenerate the formations at 8
        -- first, or it is refused for the count mismatch like anything else.
        rehearsal = {
            { formation = "ring",          place = "stage", morph = 0,     hold = 2000, color = "white", lit = false },
            { formation = "ring",          place = "stage", morph = 0,     hold = 3000, color = "cyan" },
            { formation = "seventy_seven", place = "stage", morph = 19000, hold = 5000, color = "amber" },
            { formation = "seventy_seven", place = "stage", morph = 0,     hold = 1000, color = "amber", lit = false },
        },
    },
    defaultShow = "open77",
}
